[phases.build]
cmds = [
  "yarn install",
  "yarn build",
  "cd dashboard && npm install",
  "cd dashboard && npm run build"
]

[start]
cmd = "yarn start"

[variables]
NODE_ENV = "production"
PORT = "3000"
NIXPACKS_NODE_VERSION = "20"
